config/routes.rb
Rails.application.routes.draw do

  constraints(Subdomain) do

    scope :config do
      resources :teams, except: [:show]
      resources :surveys do
        resources :fields do
          resources :field_choices
        end
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :clinics, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :providers, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      # resources :devices, except: [:show] do
      #   collection do
      #     get 'archived'
      #   end
      #   member do
      #     get 'restore'
      #     delete 'archive'
      #   end
      # end
      resources :locations, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :services, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      root to: redirect('/config/surveys'), as: 'config_root'
    end

    scope :chart do
      get 'recent_responses_chart' => 'responses#recent_responses_chart'
      get 'clinic_usage_chart' => 'responses#clinic_usage_chart'
      get 'multiple_choice_chart' => 'responses#multiple_choice_chart'
    end
    get 'dashboard' => 'responses#index'
    post 'dashboard' => 'responses#index'

    get '/install', to: redirect('/install/new')
    resource :install, only: [:new, :create, :edit], as: 'installs'
    post 'install/:id' => 'installs#update', as: 'device'

    devise_for :users,
      controllers: {
        :invitations => 'users/invitations',
        :registrations => 'users/registrations'
      },
      skip: [:sessions]

    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
      get "profile" => "users/registrations#edit"
      resources :users, except: [:show]
    end

    get "/kiosk/:survey_guid/:clinic_guid" => 'kiosk#new', constraints: { survey_guid: /[a-z0-9\-]+/, clinic_guid: /[a-z0-9\-]+/ }, as: "new_response"
    post "/kiosk/:survey_guid/:clinic_guid" => 'kiosk#create', constraints: { survey_guid: /[a-z0-9\-]+/, clinic_guid: /[a-z0-9\-]+/ }, as: "responses"

    get '/', to: redirect('/dashboard')
  end

  namespace :api, defaults: {format: :json} do
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
    resources :surveys do
      resources :fields do
        resources :field_choices
      end
      resources :clinics do
        resources :providers
      end
    end
    get 's3/token'
  end

  get 'get-started' => 'teams#new', constraints: {subdomain: /(www)?/x}
  post 'get-started' => 'teams#create', constraints: {subdomain: /(www)?/x}

  root :to => 'home#index', constraints: {subdomain: /(www)?/x}

  get '/templates/:path.html' => 'angular#template', :constraints => { :path => /.+/  }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  include Filterable, ChartData
  acts_as_paranoid

  belongs_to :team, :inverse_of => :surveys

  has_and_belongs_to_many :clinics
  has_many :responses, inverse_of: :survey, dependent: :destroy
  has_many :fields, -> { order("priority ASC") }, inverse_of: :survey, dependent: :destroy

  scope :guid, -> (guid) { where(guid: guid).first }
  store :opts, :accessors => [:intro_id, :outro_id, :logo_path], coder: JSON
  
  before_validation :translate_slug, on: :create

  validates :title, presence: true
  validates :guid, presence: true, uniqueness: { scope: :team, message: " exists for this team." }

  def translate_slug
    self.guid = self.title.parameterize('-')
  end

  # Calculates the average time for responses
  def average_time
    return nil if self.responses.size == 0
    Time.at( self.responses.map(&:time).inject([0.0,0]) { |r,el| [r[0]+el, r[1]+1] }.inject(:/) ).utc.strftime("%H:%S") unless count == 0
  end

  def clinics_count
    self.clinics.count
  end

  def providers_count
    self.clinics.includes(:providers).map { |c| c.providers.length }.inject(0) { |sum,item| sum + item }
  end

  def data_fields
    self.fields.where.not(context: Field::DATA_EXCLUDE)
  end

end

app/controllers/api/surveys_controller.rb
class Api::SurveysController < Api::BaseController
  before_action :set_survey, only: [:show, :update, :destroy]
  skip_before_filter :authenticate_user, :only => :index

  # GET /api/surveys
  def index
    @surveys = current_team.surveys.filter(params.slice(:guid))
  end

  # GET /api/surveys/1
  def show
  end

  # POST /api/surveys
  def create
    @survey = current_team.surveys.new(survey_params)
    respond_to do |format|
      if @survey.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/surveys/1
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/surveys/1
  def destroy
    @survey.destroy
    render nothing: true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey ||= current_team.surveys.find(params[:id] || params[:guid])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_params
    params.require(:survey).permit(:title, :description, :guid, :intro_id, :outro_id, :logo_path, :status, :scheduled, :scheduled_start, :scheduled_stop)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ConfigController
  authorize_resource
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :archive]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = current_team.surveys.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = current_team.surveys.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = current_team.surveys.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_fields_url(@survey), notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to edit_survey_url, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.really_destroy!
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /surveys/archived
  def archived
    @surveys = current_team.surveys.only_deleted
  end

  # GET /surveys/1/restore
  def restore
    Survey.restore(params[:id], recursive: true)

    respond_to do |format|
      format.html { redirect_to archived_surveys_url, notice: 'Survey was successfully restored.' }
      format.json { render :show, status: :ok }
    end
  end

  # DELETE /surveys/1/delete
  # DELETE /surveys/1/delete.json
  def archive
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully archived.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = current_team.surveys.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:team_id, :title, :description, :guid, :status)
    end

end

app/helpers/api/survey_helper.rb
module Api::SurveyHelper
  def status
    [
      ["Draft", "draft"],
      ["Published", "published"]
    ]  
  end  
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.slim
.block-panel
  .content
    = form_for @survey do |f|
      - if @survey.errors.any?
        .alert-box.alert.radius
          = "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved: "
          strong = @survey.errors.full_messages.join(", ")

      .form-header
        .header
          h3 = t 'surveys.form.details.title'

      .form-group
        .full
          = f.label :title
          = f.text_field :title, class: 'radius'
      .form-group
        .full
          = f.label :description
          = f.text_field :description, class: 'radius'

      .form-header
        .header
          h3 = t 'surveys.form.guid.title'

      .form-group
        .full
          p = t('surveys.form.guid.describe', url: "#{request.protocol}#{current_team.subdomain}.#{request.domain}/kiosk/").html_safe
          
          - if @survey.status == 'draft'
            = f.text_field :guid, placeholder: "e.g. my-super-inquisitive-survey", class: 'radius'
            - if action_name != 'new'
              .alert-box.warning.radius
                | Changing the slug is not recommended. Consider yourself warned!

          - if @survey.status == 'published'
            = f.text_field :guid, readonly: "readonly", class: 'radius' if @survey.status == 'published'
            .alert-box.warning.radius
              | This survey has been published, changing the slug is absolutely forbidden!

      .form-buttons
        .full
          = f.submit 'Save Survey', class: 'radius success button' 
          = link_to 'Cancel', surveys_path, class: 'radius secondary button', target: "_self"
          = link_to 'Archive', @survey, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'radius alert button pull-right' if (can? :destroy, Survey) && action_name == 'edit'

app/views/surveys/_header.html.slim
section.section.section-toolbox

  div.toolbox-header
    hgroup
      = link_to '← Back to Surveys', surveys_path, target: "_self", class: "back-link" if action_name != 'index'
      h2 = t "surveys.#{action_name}.title"
      h3.subheader = t "surveys.#{action_name}.describe"
      
  div.toolbox-actions
    - if action_name == 'index'

      - if can? :create, Survey
        = link_to 'New Survey', new_survey_path, target: "_self", class: "large radius success button"
      
      - if can?(:update, Survey) && current_team.surveys.only_deleted.size > 0
        div = link_to pluralize(current_team.surveys.only_deleted.count, 'archived survey'), archived_surveys_path, target: "_self", class: "color-alert link"
    
    - if action_name == 'archived'
      button.large.alert.radius.button.right disabled="disabled" Remove All

app/views/surveys/archived.html.slim
section.section.section-survey-archive
  article.article-content

    .block
      - @surveys.sort.each do |survey|
        .block-item.alert-light
          .details
            .name = survey.title
          .options
            ul.actions
              li = link_to restore_survey_path(survey), target: "_self"
                i.fa.fa-refresh
              - if can? :destroy, survey
                li = link_to survey_path(survey), data: {:confirm => 'Are you sure?'}, :method => :delete
                  i.fa.fa-trash

app/views/surveys/edit.html.slim
section.section.section-survey-edit-form
  article.article-content
    = render 'form'

app/views/surveys/index.html.slim
section.section.section-survey-collection
  article.article-content

    .block
      - @surveys.sort.each do |survey|
        .block-item
          .details
            .status class="#{survey.status}"
              i.fa.fa-circle
            .name
              = survey.title
              span.muted = " is #{survey.status} with #{pluralize(survey.clinics.count, 'clinic')}"

          .options
            ul.actions
              - if can? :manage, Field
                li
                  = link_to survey_fields_path(survey), target: "_self", tooltip: "Fields"
                    i.fa.fa-th-list

              - if can? :update, survey
                li
                  = link_to edit_survey_path(survey), target: "_self", tooltip: "Settings"
                    i.fa.fa-cog

app/views/surveys/new.html.slim
section.section.section-survey-new-form
  article.article-content
    = render 'form'