config/routes.rb
Rails.application.routes.draw do

  constraints(Subdomain) do

    scope :config do
      resources :teams, except: [:show]
      resources :surveys do
        resources :fields do
          resources :field_choices
        end
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :clinics, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :providers, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      # resources :devices, except: [:show] do
      #   collection do
      #     get 'archived'
      #   end
      #   member do
      #     get 'restore'
      #     delete 'archive'
      #   end
      # end
      resources :locations, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      resources :services, except: [:show] do
        collection do
          get 'archived'
        end
        member do
          get 'restore'
          delete 'archive'
        end
      end
      root to: redirect('/config/surveys'), as: 'config_root'
    end

    scope :chart do
      get 'recent_responses_chart' => 'responses#recent_responses_chart'
      get 'clinic_usage_chart' => 'responses#clinic_usage_chart'
      get 'multiple_choice_chart' => 'responses#multiple_choice_chart'
    end
    get 'dashboard' => 'responses#index'
    post 'dashboard' => 'responses#index'

    get '/install', to: redirect('/install/new')
    resource :install, only: [:new, :create, :edit], as: 'installs'
    post 'install/:id' => 'installs#update', as: 'device'

    devise_for :users,
      controllers: {
        :invitations => 'users/invitations',
        :registrations => 'users/registrations'
      },
      skip: [:sessions]

    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
      get "profile" => "users/registrations#edit"
      resources :users, except: [:show]
    end

    get "/kiosk/:survey_guid/:clinic_guid" => 'kiosk#new', constraints: { survey_guid: /[a-z0-9\-]+/, clinic_guid: /[a-z0-9\-]+/ }, as: "new_response"
    post "/kiosk/:survey_guid/:clinic_guid" => 'kiosk#create', constraints: { survey_guid: /[a-z0-9\-]+/, clinic_guid: /[a-z0-9\-]+/ }, as: "responses"

    get '/', to: redirect('/dashboard')
  end

  namespace :api, defaults: {format: :json} do
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
    resources :surveys do
      resources :fields do
        resources :field_choices
      end
      resources :clinics do
        resources :providers
      end
    end
    get 's3/token'
  end

  get 'get-started' => 'teams#new', constraints: {subdomain: /(www)?/x}
  post 'get-started' => 'teams#create', constraints: {subdomain: /(www)?/x}

  root :to => 'home#index', constraints: {subdomain: /(www)?/x}

  get '/templates/:path.html' => 'angular#template', :constraints => { :path => /.+/  }
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  include Filterable
  acts_as_paranoid

  # default_scope { order('providers.surname ASC') }

  # Exclude these field contexts in the dashboard
  DASHBOARD_CONTEXT_EXCLUDE = %w(intro outro provider_dropdown)

  belongs_to :team, inverse_of: :providers

  belongs_to :clinic, inverse_of: :providers # remove this later
  has_and_belongs_to_many :clinics
  
  has_many :responses, inverse_of: :provider, dependent: :destroy

  # Strip attributes from whitespaces
  auto_strip_attributes :name, :surname, :credential, :email

  # This method associates the attribute ":logo" with a file attachment
  has_attached_file :photo, 
    styles: {
      large: "800x640>",
      medium: "400x320>",
      thumb: "200x160>"
    },
    convert_options: {
      large: "-strip",
      medium: "-strip"
    }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  # Validate the attached image is at least 800x640
  validates :photo, :dimensions => { :width => 800, :height => 640 }

  validates_presence_of :name
  validates_presence_of :surname

  def average_time
    avg = 0.0
    self.responses.each_with_index do |response, index|
      avg = ((response.time + (avg * index.to_f)) / (index.to_f + 1)).to_f
    end

    Time.at(avg).utc.strftime("%M:%S")
  end

  def fields
    self.clinic.survey.fields
  end

  def full_name
    "#{self.name} #{self.surname}, #{self.credential}"
  end

  def full_name_surname_first
    "#{self.surname} #{self.credential}, #{self.name}"
  end

  def data_fields
    self.clinic.survey.fields.includes(:field_choices).where.not(context: Field::DATA_EXCLUDE)
  end

  def data
    
  end

  private

  def require_at_least_one_clinic
    if clinics.count == 0
      errors.add :clinic_ids, "Please select at least one Clinic"
    end
  end

  def flat_number
    phone.gsub(/[^0-9]/, '')
  end
  
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  layout 'angular'

  def index
  end

  def template
    render :template => 'angular/' + params[:path], :layout => nil
  end
end

app/controllers/api/providers_controller.rb
class Api::ProvidersController < Api::BaseController
  before_action :set_provider, only: [:show, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = clinic.providers.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = clinic.providers.new(provider_params)
    
    respond_to do |format|
      if @provider.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    render nothing: true
  end

  private

    def survey
      @survey ||= current_team.surveys.find(params[:survey_id])
    end

    def clinic
      @clinic ||= survey.clinics.find(params[:clinic_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider ||= clinic.providers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :position, :email, :phone, :clinic, :photo)
    end
end

app/controllers/providers_controller.rb
class ProvidersController < ConfigController
  authorize_resource
  before_action :set_provider, only: [:show, :edit, :update, :destroy, :archive]

  # GET /providers
  # GET /providers.json
  def index
    @providers = current_team.providers.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = current_team.providers.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = current_team.providers.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to providers_url, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to providers_url, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.really_destroy!
    respond_to do |format|
      format.html { redirect_to archived_providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /providers/archived
  def archived
    @providers = current_team.providers.only_deleted
  end

  # GET /providers/1/restore
  def restore
    Provider.restore(params[:id], recursive: true)

    respond_to do |format|
      format.html { redirect_to archived_providers_url, notice: 'Provider was successfully restored.' }
      format.json { render :show, status: :ok }
    end
  end

  # DELETE /providers/1/delete
  # DELETE /providers/1/delete.json
  def archive
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully archived.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = current_team.providers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :surname, :credential, :team_id, :position, :email, :phone, :photo, {clinic_ids: []})
    end

end

app/helpers/api/provider_helper.rb
module Api::ProviderHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/angular/providers/_form.html.slim
form.form-horizontal role="form" name="providerForm" autocomplete="off" novalidate="novalidate"
  
  .form-group
    label.control-label.col-sm-2 for="name" Name
    .col-sm-10
      input.form-control#name type="text" name="name" ng-model="provider.name" autocomplete="off" required="required"

  .form-group
    label.control-label.col-sm-2 for="position" Position
    .col-sm-10
      input.form-control#position type="text" name="position" ng-model="provider.position" autocomplete="off" required="required"

  .form-group
    label.control-label.col-sm-2 for="email" Email
    .col-sm-10
      input.form-control#email type="email" name="email" ng-model="provider.email" autocomplete="off" required="required"

  .form-group
    label.control-label.col-sm-2 for="phone" Phone
    .col-sm-6
      input.form-control#phone type="tel" name="phone" ng-model="provider.phone" autocomplete="off" mask="phone"
  
  .form-group.hide
    label.control-label.col-sm-2 for="photo_url" Photo
    .col-sm-6
      div s3-upload="" bucket="'salubrity'" ng-model="provider.photo" s3-upload-options="{getOptionsUri: s3OptionsUri, folder: '{{clinic.id}}/providers/'}"

app/views/angular/providers/edit.html.slim
.ng-cloak ng-init="init()"
  
  .modal-header
    h3 Edit Provider
    button.close.md-close type="button" aria-hidden="true" ng-click="close()" ×

  .modal-body.form
    = render 'angular/providers/form'

  .modal-footer
    button.btn.btn-default.btn-rad.btn-flat ng-click="close()" Cancel
    button.btn.btn-success.btn-rad.btn-flat ng-click="proceed(provider)" ng-disabled="providerForm.$invalid" Save Provider

app/views/angular/providers/index.html.slim
h1 Listing providers

table
  thead
    tr
      th Name
      th Position
      th Email
      th Phone
      th Clinic
      th Photo
      th
      th
      th

  tbody
    - @providers.each do |provider|
      tr
        td = provider.name
        td = provider.position
        td = provider.email
        td = provider.phone
        td = provider.clinic
        td = provider.photo
        td = link_to 'Show', provider
        td = link_to 'Edit', edit_provider_path(provider)
        td = link_to 'Destroy', provider, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Provider', new_provider_path

app/views/angular/providers/list.html.slim
.row.no-margin
  .col-md-11.user-list
    
    button.btn.btn-success.pull-right ng-click="addProvider()" New Provider
    h3 Providers

    .block-flat.user-block ng-repeat="provider in clinic.providers | orderBy:predicate"
      .tools.pull-right
        button.btn.btn-primary.btn-flat ng-click="editProvider(provider)" tooltip="Edit provider" tooltip-placement="left"
          i.fa.fa-pencil
        button.btn.btn-danger.btn-flat ng-click="deleteProvider(provider)" tooltip="Delete provider" tooltip-placement="right"
          i.fa.fa-trash-o

      h4
        | {{provider.name}}

app/views/angular/providers/new.html.slim
.ng-cloak ng-init="init()"
  
  .modal-header
    h3 New Provider
    button.close.md-close type="button" aria-hidden="true" ng-click="close()" ×

  .modal-body.form
    = render 'angular/providers/form'

  .modal-footer
    button.btn.btn-default.btn-rad.btn-flat ng-click="close()" Cancel
    button.btn.btn-success.btn-rad.btn-flat ng-click="proceed(provider)" ng-disabled="providerForm.$invalid" Create Provider

app/views/angular/providers/show.html.slim
p#notice = notice

p
  strong Name:
  = @provider.name
p
  strong Position:
  = @provider.position
p
  strong Email:
  = @provider.email
p
  strong Phone:
  = @provider.phone
p
  strong Clinic:
  = @provider.clinic
p
  strong Photo:
  = @provider.photo

= link_to 'Edit', edit_provider_path(@provider)
'|
= link_to 'Back', providers_path